# Generated by Django 3.2.16 on 2022-12-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221225_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ("Qayta qo'ng'iroq", "Qayta qo'ng'iroq"), ('Qabul qilindi', 'Qabul qilindi'), ('Spam', 'Spam'), ('Yetkazilmoqda', 'Yetkazilmoqda'), ('Yetkazib berildi', 'Yetkazib berildi'), ('Rad qilindi', 'Rad qilindi')], default='Yangi', max_length=212),
        ),
    ]
